package com.example.MyBookShoppApp.model.book.review;

import com.example.MyBookShoppApp.keys.BookUserId;
import com.example.MyBookShoppApp.model.oldEntity.Book;
import com.example.MyBookShoppApp.model.user.UserEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;
import java.time.LocalDateTime;

@Entity
@Table(name = "book_review")
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode
@ApiModel(description = "Book's review from users")
public class BookReviewEntity implements Serializable {

    @EmbeddedId
    @ApiModelProperty(value = "Id generated by DB", example = "1", position = 1)
    private BookUserId pk = new BookUserId();

    @Column(columnDefinition = "date NOT NULL")
    @ApiModelProperty(value = "Time generated automatically", example = "2022-09-06", position = 2)
    private LocalDateTime time;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty(value = "Text about this book.", position = 3)
    private String text;

    public Book getBook() {
        return getPk().getBook();
    }

    public UserEntity getUserEntity() {
        return getPk().getUser();
    }

    public void setBook(Book book){
        getPk().setBook(book);
    }

    public void setUser(UserEntity user){
        getPk().setUser(user);
    }
}
